### PR TITLE
created events

### LINKED ISSUE #110: create events for when a flag is added or removed

### PR DESCRIPTION
**Pull request by lukesmurray**
closes #110

### CODE REVIEW

**Comment by lukesmurray** [comment]
So flag added is now working but there are a couple of bugs which need to be resolved. In the front end and the backend.

## Front End

- [ ] We need two types for the flag events, flag added and flag removed instead of the single type flag changed
- [ ] The default code for these types should be `def on_flag_added(my_message, added_flags)` and `def on_flag_removed(my_message, removed_flags)` since the added or removed flags are a list not a single flag.
- [ ] The flag rules do not show up in a new tab. we should probably look at the code we are using to create a new tab since it currently feels hard to maintain 
- [ ] The current debugging interface only works for events associated with a single message we should discuss what we want to have happen if there is another type of event we need to log. (Maybe all events are associated with a single message?)
 - [ ] The import statements are currently broken in the default code. we either need to add `spacy` and `arrow` to `requirements.docker.txt` or we need to remove those two libraries from the default imports. Also it doesn't make much sense to import default python libraries. Users can do that themselves if they want to.

## Back End
- [ ] user methods in sandbox.py should be moved to mailbox.py
- [ ] we also have the assumption in sandbox.py that events are associated with a message. This is a coupling between the front end logging system and the back end

One suggestion for how we could limit the coupling between the backend and the front end as well as the messiness in sandbox.py. 

- Move the logging into fire_event. fire_event can return a loggable object which is then returned to the front end. The front end takes on the responsibility of displaying that object to the user. This maintains the abstraction on events so that we don't have to do if statements on every event type

**Comment by lukesmurray** [comment]
closes #113

**Comment by soyapark** [comment]
> * Move the logging into fire_event. fire_event can return a loggable object which is then returned to the front end. The front end takes on the responsibility of displaying that object to the user. This maintains the abstraction on events so that we don't have to do if statements on every event type

The reason I didn't put into fire_event is to log everything even if it is not fired s.t. there is a new email arrived and users didn't set up the rules for new emails, users still have to be able to see the message arrival log. 

> ## Gmail
> * [ ]  I'm actually not sure if the gmail interface offers a method to add flags directly. I've been testing by marking messages as read.
Yes, you can add Gmail label at the interface. I'm not sure how you've been tracking gmail user's label but it is different than imap label.

**Comment by lukesmurray** [comment]
this now works. Feel free to test it but I believe it is ready to review

**Pull request merged**
